### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Goldinium** [Al-Amin-Khan-Shakil/ruby-group-capstone-project#43]
Hello

This is the Ruby Capstone Group Project

Team members are:

Team member #2 @Goldinium
Team member #1 @Al-Amin-Khan-Shakil
Team member #3 @lucy-sees
Team member #4 @evansnyamekye

Capstone Project link is:
https://github.com/Al-Amin-Khan-Shakil/ruby-group-capstone-project

Kanban Board Project link:
https://github.com/Al-Amin-Khan-Shakil/ruby-group-capstone-project/projects/1

**Comment by julie-ify** [comment]
Hi @Goldinium, @evansnyamekye, @lucy-sees and @Al-Amin-Khan-Shakil,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly specify the kanban project link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Goldinium** [comment]
Done

**Comment by julie-ify** [comment]
## Hi @Goldinium, @evansnyamekye, @lucy-sees and @Al-Amin-Khan-Shakil,

Good job so far!

## Highlights!
- Good task organization ✔️
- Good task descriptions ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Team member #1 is missing this task. Kindly include it.

  ![image](https://github.com/Al-Amin-Khan-Shakil/ruby-group-capstone-project/assets/81468675/873b9db6-792d-44cb-983f-85f86334c199)

- [ ] Team member #4 is missing this task. Kindly include it.

  ![image](https://github.com/Al-Amin-Khan-Shakil/ruby-group-capstone-project/assets/81468675/1cc4cd47-6b42-4c89-8d0e-010d83abdf9d)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Abenezer-Tilahun** [comment]
Hi @Goldinium @evansnyamekye @Al-Amin-Khan-Shakil 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻
✔️ Correctly Set up Ruby group capstone: set up your Kanban board
✔️ Correctly organization and description about the number of people in group.
✔️ Good job for Implemented Suggested changes.



## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
